---
title: "Actividades_Andres_chavez_30_oct"
output: html_document
date: "2024-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Archivo en R Markdown

Aqui estan los ejercicios realizados

## Ejercicio 1

```{r}
tetralista <- list(
  numero = 466458,
  vector = c(69, 25, 76, 65, 77),
  matriz = matrix(c(85, 64, 79, 47,69,115), ncol =3),
  data_frame = data.frame(nombre = c("Bacillus. ", "Salmonella"), gram = c("+", "-"))
)
tetralista

# Accediendo a los datos por indice
numerillo <- tetralista$numero
print(numerillo)

vectorcillo <- tetralista$vector
print(vectorcillo)

matrixcilla <- tetralista$matriz
print(matrixcilla)

framecillo <- tetralista$data_frame
print(framecillo)
```

## Ejercicio 2

```{r}
tetralista_modificada <- list(
  numero = 466458,
  vector = c(69, 25, 76, 65, 77),
  matriz = matrix(c(85, 64, 79, 47,69,115), ncol =3),
  data_frame = data.frame(nombre = c("Bacillus. ", "Salmonella"), gram = c("+", "-")),
  
 datos_microbiologicos_2da_lista=datos_de_crecimiento<-list(
    cepas<- c("Y.pestis","E.coli","V.cholerae"),
    resultados_de_crecimiento<- c("Y.pestis,CRECIO","E.coli NO CRECIO","V.cholerae CRECIO"),
    tipo_de_medio_de_cultivo<- c("Agar sangre","Agar mckonkey")
  )
)
tetralista_modificada

cepas_usadas<-cepas
print(cepas_usadas)

```

## Ejercicio 3

```{r}
#Crea una lista resistencias con 3 elementos, cada uno representando una bacteria.
#Cada elemento debe ser una lista con: Bacteria, 
#AntibióticosResistentes (vector de nombres de antibióticos).
#Encuentra la bacteria con más resistencias.
Perfil_de_resistencias<-list(
  Bacteria<- c("V.cholerae"),
  Antibioticos_resistentes<- as.numeric("cloranfenicol","tetraciclina","carbapenemicos"),
 Perfil_de_resistencias2<-list(
  Bacteria<- c("Y.pestis"),
  Antibioticos_resistentes<- as.numeric("cloranfenicol","tetraciclina","carbapenemicos"),
 Perfil_de_resistencias3<-list(
  Bacteria<- c("E.coli"),
  Antibioticos_resistentes<- as.numeric("cloranfenicol","tetraciclina","carbapenemicos")
 
)

Antibioticos_resistentes<-c("cloranfenicol","tetraciclina","carbapenemicos")
Antibioticos_resistentes
Antibioticos_resistentes2<-c("cloranfenicol","tetraciclina","carbapenemicos","sdvas")
Antibioticos_resistentes2
Antibioticos_resistentes3<-c("cloranfenicol","tetraciclina","carbapenemicos","safda","asfad")
Antibioticos_resistentes3
mayor_resistente<-c(Antibioticos_resistentes,Antibioticos_resistentes2,Antibioticos_resistentes3)
mayor_resistente
mayor_resistente2<- which(mayor_resistente >3)
mayor_resistente2

#por tiempo ya no pude completarlo bien, intente hacer el codigo para determinar las mas resistentes
```
